# adapted from https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install .
script:
  - python setup.py test
  - python hplusminus_tests.py ./examples/true_model_normalized_residuals.txt
